insert into beeromon_power_by_type values(0,16);
insert into beeromon_power_by_type values(0,2);
insert into beeromon_power_by_type values(0,3);

insert into beeromon_power_by_type values(1,13);
insert into beeromon_power_by_type values(1,7);
insert into beeromon_power_by_type values(1,4);

insert into beeromon_power_by_type values(2,9);
insert into beeromon_power_by_type values(2,11);
insert into beeromon_power_by_type values(2,5);
insert into beeromon_power_by_type values(3,12);
insert into beeromon_power_by_type values(3,10);
insert into beeromon_power_by_type values(3,8);
insert into beeromon_power_by_type values(4,7);
insert into beeromon_power_by_type values(4,15);
insert into beeromon_power_by_type values(4,1);
insert into beeromon_power_by_type values(5,2);
insert into beeromon_power_by_type values(5,6);
insert into beeromon_power_by_type values(5,10);
insert into beeromon_power_by_type values(6,5);
insert into beeromon_power_by_type values(6,19);
insert into beeromon_power_by_type values(6,6);
insert into beeromon_power_by_type values(7,8);
insert into beeromon_power_by_type values(7,15);
insert into beeromon_power_by_type values(7,1);
insert into beeromon_power_by_type values(8,14);
insert into beeromon_power_by_type values(8,10);
insert into beeromon_power_by_type values(8,3);
insert into beeromon_power_by_type values(9,13);
insert into beeromon_power_by_type values(9,4);
insert into beeromon_power_by_type values(9,1);
insert into beeromon_power_by_type values(10,1);
insert into beeromon_power_by_type values(10,15);
insert into beeromon_power_by_type values(10,9);
insert into beeromon_power_by_type values(11,17);
insert into beeromon_power_by_type values(11,3);
insert into beeromon_power_by_type values(11,6);
insert into beeromon_power_by_type values(12,9);
insert into beeromon_power_by_type values(12,8);
insert into beeromon_power_by_type values(12,2);
insert into beeromon_power_by_type values(13,14);
insert into beeromon_power_by_type values(13,5);
insert into beeromon_power_by_type values(13,17);
insert into beeromon_power_by_type values(14,16);
insert into beeromon_power_by_type values(14,9);
insert into beeromon_power_by_type values(14,12);
insert into beeromon_power_by_type values(15,5);
insert into beeromon_power_by_type values(15,4);
insert into beeromon_power_by_type values(15,11);

insert into beeromon_power_by_type values(99 ,1);
insert into beeromon_power_by_type values(99 ,0);
insert into beeromon_power_by_type values(99 ,5);
insert into beeromon_power_by_type values(100,0);
insert into beeromon_power_by_type values(100,13);
insert into beeromon_power_by_type values(100,11);
insert into beeromon_power_by_type values(101,1);
insert into beeromon_power_by_type values(101,3);
insert into beeromon_power_by_type values(101,19);
